[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SpareFinderAI-Service"
version = "1.0.1"
description = "AI-powered automotive part identification service"
readme = "README.md"
requires-python = ">=3.8,<3.13"
license = {file = "LICENSE"}

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "mypy",
    "black",
    "isort"
]

[project.scripts]
sparefinderai-service = "app.main:main"

[tool.setuptools]
packages = ["app"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.rst", "*.md", "*.json"] 